server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/coupon?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379